### ISSUE TITLE
Deserializing custom problem type does not work

### ISSUE THREAD

**Issue by jhorstmann** [zalando/problem#36]
I want to implement a custom `IOProblem` that extends `IOException` and deserialize this from an input stream.

    final IOProblem problem = objectMapper.readValue(is, IOProblem.class);

Even though the exact class is specified, this fails with

    java.lang.AssertionError: Expected different exception type.
    Expected: an instance of org.zalando.fahrschein.IOProblem
     but: <java.lang.ClassCastException: org.zalando.problem.DefaultProblem cannot be cast to org.zalando.fahrschein.IOProblem> is a java.lang.ClassCastException
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.zalando.fahrschein.ProblemHandlingClientHttpRequestTest.recognisesJsonAndProblemBodies(ProblemHandlingClientHttpRequestTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)

The custom problem class looks like this:

    public class IOProblem extends IOException implements Problem {
        private final URI type;
        private final String title;
        private final Response.StatusType status;
        private final Optional<String> detail;
        private final Optional<URI> instance;
    
        @JsonCreator
        public IOProblem(@JsonProperty("type") URI type, @JsonProperty("title") String title, @JsonProperty("status") int status, @JsonProperty("detail") Optional<String> detail, @JsonProperty("instance") Optional<URI> instance) {
            super(formatMessage(type, title, status));
            this.type = type;
            this.title = title;
            this.status = Response.Status.fromStatusCode(status);
            this.detail = detail;
            this.instance = instance;
        }

        ...

    }

**Comment by whiskeysierra** [comment]
@jhorstmann I think the issue is that `IOProblem` *is* a `Problem`, but it doesn't have a `@JsonTypeName` annotation which it needs to play nicely with `ProblemMixin`, which declares a `@JsonTypeInfo`. Jackson acts based on the assumption that all subtypes are honoring this contract. You can disable the type handling by adding the following annotation to your class:

```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NONE)
public final class IOProblem extends IOException implements Exceptional {

    ...

}
```
