### ISSUE TITLE
Support non-numeric status types in StatusTypeDeserializer

### ISSUE THREAD

**Issue by jhorstmann** [zalando/problem#48]
Just ran across a problem:

    {
      "type": "http://httpstatus.es/422",
      "title": "Required data not found",
      "status": "422",
      "detail": "..."
    }

Which fails deserialization with:

    Caused by: org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Current token (VALUE_STRING) not numeric, can not use numeric value accessors
     at [Source: java.io.ByteArrayInputStream@418c5a9c; line: 1, column: 80] (through reference chain: org.zalando.problem.DefaultProblem["status"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Current token (VALUE_STRING) not numeric, can not use numeric value accessors
     at [Source: java.io.ByteArrayInputStream@418c5a9c; line: 1, column: 80] (through reference chain: org.zalando.problem.DefaultProblem["status"])
            at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:208)
            at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:200)
            at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:97)
            at org.zalando.riptide.TypedCondition.convert(TypedCondition.java:57)
            at org.zalando.riptide.TypedCondition.lambda$call$2(TypedCondition.java:50)
            at org.zalando.riptide.Binding.execute(Binding.java:48)
            at org.zalando.riptide.Router.route(Router.java:63)
            at org.zalando.riptide.UntypedCondition.lambda$dispatch$19(UntypedCondition.java:81)
            at org.zalando.riptide.Binding.execute(Binding.java:48)
            at org.zalando.riptide.Router.route(Router.java:63)
            at org.zalando.riptide.Dispatcher.dispatch(Dispatcher.java:45)

The problem module should probably be more liberal in what it accepts.

**Comment by AlexanderYastrebov** [comment]
Status is defined as number:
https://tools.ietf.org/html/rfc7807#section-3.1
